### ISSUE TITLE
System.ArgumentException: 'Source array was not long enough on latest Bouncy Castle dll v2.4.0

### ISSUE THREAD

**Issue by Deltafox79** [filipw/Strathweb.Samples.CSharp.Crystals#2]
Whit latest BouncyCastle.Cryptography.dll v2.4.0

on line 68:
  
var signature2 = aliceRecovered.GenerateSignature(**data**);

cause **System.ArgumentException** :

**System.ArgumentException: 'Source array was not long enough. Check the source index, length, and the array's lower bounds. Arg_ParamName_Name'**

**change** 

aliceRecovered.Init(true, **recoveredKey**);

**whit** 

aliceRecovered.Init(true, **privateKey**);

Resolve the issue...

Regards

**Comment by filipw** [comment]
The thing is with your change the key is no longer extracted from the export.
This is fixed in https://github.com/filipw/Strathweb.Samples.CSharp.Crystals/pull/3

Thanks for reporting

**Comment by Deltafox79** [comment]
Tks also Spectre.Console update to v 0.49.1.. Regards
